/* ---------------------------- Formations -------------------------------- */
// Pitch coordinate system: x 0-100 (left-right), y 8 (opponent goal, top) -> 92 (own goal, bottom)
export const FORMATIONS = {
  "4-3-3": { label: "4-3-3", slots: [
    { id: "GK", type: "GK", x: 50, y: 92 },
    { id: "LB", type: "FB", side: "L", x: 14, y: 72 },
    { id: "CB1", type: "CB", x: 36, y: 79 },
    { id: "CB2", type: "CB", x: 64, y: 79 },
    { id: "RB", type: "FB", side: "R", x: 86, y: 72 },
    { id: "CM1", type: "CM", x: 28, y: 52 },
    { id: "CM2", type: "CM", x: 50, y: 46 },
    { id: "CM3", type: "CM", x: 72, y: 52 },
    { id: "LW", type: "WIDE", side: "L", x: 16, y: 22 },
    { id: "ST", type: "ST", x: 50, y: 12 },
    { id: "RW", type: "WIDE", side: "R", x: 84, y: 22 },
  ]},
  "4-4-2": { label: "4-4-2", slots: [
    { id: "GK", type: "GK", x: 50, y: 92 },
    { id: "LB", type: "FB", side: "L", x: 14, y: 72 },
    { id: "CB1", type: "CB", x: 36, y: 79 },
    { id: "CB2", type: "CB", x: 64, y: 79 },
    { id: "RB", type: "FB", side: "R", x: 86, y: 72 },
    { id: "LM", type: "WIDE", side: "L", x: 14, y: 46 },
    { id: "CM1", type: "CM", x: 38, y: 50 },
    { id: "CM2", type: "CM", x: 62, y: 50 },
    { id: "RM", type: "WIDE", side: "R", x: 86, y: 46 },
    { id: "ST1", type: "ST", x: 40, y: 15 },
    { id: "ST2", type: "ST", x: 60, y: 15 },
  ]},
  "4-2-3-1": { label: "4-2-3-1", slots: [
    { id: "GK", type: "GK", x: 50, y: 92 },
    { id: "LB", type: "FB", side: "L", x: 14, y: 72 },
    { id: "CB1", type: "CB", x: 36, y: 79 },
    { id: "CB2", type: "CB", x: 64, y: 79 },
    { id: "RB", type: "FB", side: "R", x: 86, y: 72 },
    { id: "DM1", type: "DM", x: 37, y: 58 },
    { id: "DM2", type: "DM", x: 63, y: 58 },
    { id: "AML", type: "AM", x: 20, y: 33 },
    { id: "AMC", type: "AM", x: 50, y: 30 },
    { id: "AMR", type: "AM", x: 80, y: 33 },
    { id: "ST", type: "ST", x: 50, y: 12 },
  ]},
  "3-5-2": { label: "3-5-2", slots: [
    { id: "GK", type: "GK", x: 50, y: 92 },
    { id: "CB1", type: "CB", x: 26, y: 77 },
    { id: "CB2", type: "CB", x: 50, y: 81 },
    { id: "CB3", type: "CB", x: 74, y: 77 },
    { id: "WBL", type: "FB", side: "L", x: 8, y: 50 },
    { id: "CM1", type: "CM", x: 34, y: 53 },
    { id: "CM2", type: "CM", x: 50, y: 46 },
    { id: "CM3", type: "CM", x: 66, y: 53 },
    { id: "WBR", type: "FB", side: "R", x: 92, y: 50 },
    { id: "ST1", type: "ST", x: 40, y: 15 },
    { id: "ST2", type: "ST", x: 60, y: 15 },
  ]},
  "3-4-3": { label: "3-4-3", slots: [
    { id: "GK", type: "GK", x: 50, y: 92 },
    { id: "CB1", type: "CB", x: 26, y: 77 },
    { id: "CB2", type: "CB", x: 50, y: 81 },
    { id: "CB3", type: "CB", x: 74, y: 77 },
    { id: "WBL", type: "FB", side: "L", x: 8, y: 50 },
    { id: "CM1", type: "CM", x: 38, y: 50 },
    { id: "CM2", type: "CM", x: 62, y: 50 },
    { id: "WBR", type: "FB", side: "R", x: 92, y: 50 },
    { id: "LW", type: "WIDE", side: "L", x: 18, y: 19 },
    { id: "ST", type: "ST", x: 50, y: 12 },
    { id: "RW", type: "WIDE", side: "R", x: 82, y: 19 },
  ]},
  "5-3-2": { label: "5-3-2", slots: [
    { id: "GK", type: "GK", x: 50, y: 92 },
    { id: "WBL", type: "FB", side: "L", x: 8, y: 68 },
    { id: "CB1", type: "CB", x: 30, y: 78 },
    { id: "CB2", type: "CB", x: 50, y: 82 },
    { id: "CB3", type: "CB", x: 70, y: 78 },
    { id: "WBR", type: "FB", side: "R", x: 92, y: 68 },
    { id: "CM1", type: "CM", x: 30, y: 48 },
    { id: "CM2", type: "CM", x: 50, y: 43 },
    { id: "CM3", type: "CM", x: 70, y: 48 },
    { id: "ST1", type: "ST", x: 40, y: 15 },
    { id: "ST2", type: "ST", x: 60, y: 15 },
  ]},
  "4-1-4-1": { label: "4-1-4-1", slots: [
    { id: "GK", type: "GK", x: 50, y: 92 },
    { id: "LB", type: "FB", side: "L", x: 14, y: 72 },
    { id: "CB1", type: "CB", x: 36, y: 79 },
    { id: "CB2", type: "CB", x: 64, y: 79 },
    { id: "RB", type: "FB", side: "R", x: 86, y: 72 },
    { id: "DM", type: "DM", x: 50, y: 61 },
    { id: "LM", type: "WIDE", side: "L", x: 16, y: 40 },
    { id: "CM1", type: "CM", x: 38, y: 38 },
    { id: "CM2", type: "CM", x: 62, y: 38 },
    { id: "RM", type: "WIDE", side: "R", x: 84, y: 40 },
    { id: "ST", type: "ST", x: 50, y: 12 },
  ]},
};

export const SLOT_TYPE_LABEL = { GK: "Goalkeeper", CB: "Centre-Back", FB: "Full-Back / Wing-Back", DM: "Defensive Mid", CM: "Central Mid", AM: "Attacking Mid", WIDE: "Winger", ST: "Striker" };

export function makeInitialAssignments(formationKey) {
  return FORMATIONS[formationKey].slots.map((s) => ({
    slotId: s.id, type: s.type, side: s.side || null, player: null,
    role: null, duty: null, sliderAtt: 50, sliderDef: 50, pos: { x: s.x, y: s.y },
  }));
}
